version: "3"
services:
  database:
    image: database:latest
    expose:
      - "27017"
    volumes:
      - database-volume:/data/database
    ports:
      - "27017:27017"

  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server

  server:
    build:
      context: ./server
    ports:
      - "5002:5002"
    environment:
      - MONGO_URI=mongodb://database:27017/database
    depends_on:
      - database
    volumes:
      - ./server:/app
      - /app/node_modules
    restart: on-failure
volumes:
  database-volume:
